# Generated by Django 4.1 on 2022-08-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
        ("center_library", "0002_initial"),
        ("local_library", "0002_initial"),
        ("material_application", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExWarehousingApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_code",
                    models.CharField(max_length=100, unique=True, verbose_name="申请单号"),
                ),
                (
                    "title",
                    models.CharField(max_length=100, unique=True, verbose_name="申请主题"),
                ),
                ("applicant", models.CharField(max_length=100, verbose_name="申请单位")),
                (
                    "applicant_user",
                    models.CharField(max_length=100, unique=True, verbose_name="领用人"),
                ),
                (
                    "des",
                    models.CharField(blank=True, max_length=100, verbose_name="申请说明"),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="申请时间"
                    ),
                ),
                ("add_date", models.DateField(auto_now_add=True, verbose_name="申请日期")),
                (
                    "modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "分管领导审批中"),
                            ("2", "局长审批中"),
                            ("3", "主管科室研判中"),
                            ("4", "待出库"),
                            ("5", "已出库"),
                        ],
                        default="1",
                        max_length=5,
                        verbose_name="状态",
                    ),
                ),
                (
                    "next_node",
                    models.CharField(default="", max_length=100, verbose_name="下一个审批人"),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={"verbose_name": "出库申请", "verbose_name_plural": "出库申请",},
        ),
        migrations.CreateModel(
            name="LocalAssessmentDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0, verbose_name="领用数量")),
                ("is_ex", models.BooleanField(default=0, verbose_name="是否出库")),
                (
                    "add_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="material_application.exwarehousingapplication",
                        verbose_name="申请单",
                    ),
                ),
                (
                    "library_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="local_library.locallabrarymaterials",
                        verbose_name="物资类型",
                    ),
                ),
            ],
            options={"verbose_name": "地方库研判", "verbose_name_plural": "地方库研判",},
        ),
        migrations.CreateModel(
            name="ExApplicationFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="upload/center_library/2022/8/27", verbose_name="申请资料"
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "library_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="material_application.exwarehousingapplication",
                        verbose_name="申请单编号",
                    ),
                ),
            ],
            options={"verbose_name": "申请资料", "verbose_name_plural": "申请资料",},
        ),
        migrations.CreateModel(
            name="CenterAssessmentDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0, verbose_name="领用数量")),
                ("is_ex", models.BooleanField(default=0, verbose_name="是否出库")),
                (
                    "add_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="material_application.exwarehousingapplication",
                        verbose_name="申请单",
                    ),
                ),
                (
                    "library_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="center_library.centerlabraryquantity",
                        verbose_name="物资类型",
                    ),
                ),
            ],
            options={"verbose_name": "中央库研判", "verbose_name_plural": "中央库研判",},
        ),
        migrations.CreateModel(
            name="ApplicationHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_user",
                    models.CharField(blank=True, max_length=20, verbose_name="审批人"),
                ),
                (
                    "action",
                    models.CharField(default="通过", max_length=20, verbose_name="审批动作"),
                ),
                (
                    "add_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="审批时间"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="material_application.exwarehousingapplication",
                        verbose_name="申请单",
                    ),
                ),
            ],
            options={"verbose_name": "审批记录", "verbose_name_plural": "审批记录",},
        ),
        migrations.CreateModel(
            name="ApplicationDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0, verbose_name="领用数量")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material_application.exwarehousingapplication",
                        verbose_name="申请单",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="home.materialstype",
                        verbose_name="物资类型",
                    ),
                ),
            ],
            options={"verbose_name": "领用详情", "verbose_name_plural": "领用详情",},
        ),
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_code", models.CharField(max_length=10, verbose_name="单号")),
                (
                    "db_type",
                    models.CharField(
                        choices=[("1", "地方库"), ("2", "中央库")],
                        max_length=10,
                        verbose_name="库类型",
                    ),
                ),
                ("entry_name", models.CharField(max_length=10, verbose_name="项目名称")),
                ("type_name", models.CharField(max_length=10, verbose_name="类型名称")),
                (
                    "action",
                    models.CharField(
                        choices=[("1", "入库"), ("2", "出库")],
                        max_length=10,
                        verbose_name="操作名称",
                    ),
                ),
                ("number", models.IntegerField(default=None, verbose_name="数量")),
                ("price", models.FloatField(default=None, verbose_name="金额(元)")),
                ("unit_price", models.FloatField(default=None, verbose_name="单价(元)")),
                (
                    "add_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
                (
                    "add_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="日期"
                    ),
                ),
            ],
            options={
                "verbose_name": "台账",
                "verbose_name_plural": "台账",
                "unique_together": {("app_code", "entry_name", "type_name", "db_type")},
            },
        ),
    ]
