# Generated by Django 4.1 on 2022-08-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("material_application", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="app_code",
            field=models.CharField(max_length=100, verbose_name="单号"),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="number",
            field=models.IntegerField(default=0, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="price",
            field=models.FloatField(default=0, verbose_name="金额(元)"),
        ),
        migrations.AlterField(
            model_name="applicationdetail",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.exwarehousingapplication",
                verbose_name="申请单",
            ),
        ),
    ]
