# Generated by Django 4.1 on 2022-08-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "material_application",
            "0003_alter_accounts_app_code_alter_accounts_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="entry_name",
            field=models.CharField(max_length=100, verbose_name="项目名称"),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="type_name",
            field=models.CharField(max_length=100, verbose_name="类型名称"),
        ),
    ]
