# Generated by Django 4.1 on 2022-08-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "material_application",
            "0004_alter_accounts_entry_name_alter_accounts_type_name",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="accounts", unique_together=set(),),
        migrations.AddField(
            model_name="accounts",
            name="specifications",
            field=models.CharField(default="", max_length=100, verbose_name="规格"),
        ),
        migrations.AddField(
            model_name="accounts",
            name="unit",
            field=models.CharField(default="", max_length=100, verbose_name="单位"),
        ),
        migrations.AlterUniqueTogether(
            name="accounts",
            unique_together={
                (
                    "app_code",
                    "entry_name",
                    "type_name",
                    "specifications",
                    "unit",
                    "db_type",
                )
            },
        ),
    ]
