# Generated by Django 4.1 on 2022-08-28 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("material_application", "0005_alter_accounts_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationhistory",
            options={
                "ordering": ["-add_time"],
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
            },
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="add_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="操作时间"
            ),
        ),
        migrations.AlterField(
            model_name="exapplicationfile",
            name="file",
            field=models.FileField(
                upload_to="upload/center_library/2022/8/28", verbose_name="申请资料"
            ),
        ),
        migrations.AlterField(
            model_name="exwarehousingapplication",
            name="des",
            field=models.CharField(blank=True, max_length=100, verbose_name="原因描述"),
        ),
    ]
