# Generated by Django 4.1 on 2022-08-28 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("material_application", "0006_alter_applicationhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localassessmentdetail",
            name="total_price",
            field=models.FloatField(default=0, verbose_name="领用金额(元)"),
        ),
        migrations.AlterField(
            model_name="applicationhistory",
            name="add_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="操作日期"
            ),
        ),
    ]
