# Generated by Django 4.1 on 2022-08-28 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("material_application", "0007_localassessmentdetail_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationhistory",
            name="add_time",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="操作日期"
            ),
        ),
    ]
