# Generated by Django 3.2 on 2022-08-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_application', '0008_alter_applicationhistory_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationhistory',
            options={'ordering': ['-add_time', '-id'], 'verbose_name': '审批记录', 'verbose_name_plural': '审批记录'},
        ),
        migrations.AlterModelOptions(
            name='exwarehousingapplication',
            options={'ordering': ['-add_time', '-status', '-id'], 'verbose_name': '出库申请', 'verbose_name_plural': '出库申请'},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='type_name',
            field=models.CharField(max_length=100, verbose_name='物料名称'),
        ),
        migrations.AlterField(
            model_name='exapplicationfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/8/29', verbose_name='申请资料'),
        ),
    ]
