# Generated by Django 3.2 on 2022-08-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_application', '0009_auto_20220829_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exapplicationfile',
            old_name='library_name',
            new_name='application',
        ),
        migrations.AddField(
            model_name='accounts',
            name='applicant',
            field=models.CharField(default='', max_length=100, verbose_name='申请单位'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='unit',
            field=models.CharField(default='', max_length=100, verbose_name='物料单位'),
        ),
        migrations.AlterField(
            model_name='exapplicationfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/8/30', verbose_name='申请资料'),
        ),
    ]
