# Generated by Django 3.2 on 2022-08-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('material_application', '0010_auto_20220830_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ('-add_date', 'app_code'), 'verbose_name': '台账', 'verbose_name_plural': '台账'},
        ),
        migrations.AlterUniqueTogether(
            name='applicationdetail',
            unique_together={('type_name', 'application')},
        ),
    ]
