# Generated by Django 3.2 on 2022-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_application', '0011_auto_20220830_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exapplicationfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/8/31', verbose_name='申请资料'),
        ),
    ]
