# Generated by Django 3.2 on 2022-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_application', '0012_alter_exapplicationfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exapplicationfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/9/1', verbose_name='申请资料'),
        ),
        migrations.AlterField(
            model_name='exwarehousingapplication',
            name='applicant_user',
            field=models.CharField(max_length=100, verbose_name='领用人'),
        ),
    ]
