# Generated by Django 3.2 on 2022-09-04 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_application', '0016_alter_accounts_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetail',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='领用数量'),
        ),
        migrations.AlterField(
            model_name='centerassessmentdetail',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='领用数量'),
        ),
        migrations.AlterField(
            model_name='exapplicationfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/9/4', verbose_name='申请资料'),
        ),
        migrations.AlterField(
            model_name='localassessmentdetail',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='领用数量'),
        ),
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together={('app_code', 'supplier_name', 'entry_name', 'type_name', 'specifications', 'unit', 'db_type')},
        ),
    ]
