# Generated by Django 3.2 on 2022-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_application', '0017_auto_20220904_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='exwarehousingapplication',
            name='applicant_phone',
            field=models.CharField(default='', max_length=100, verbose_name='领用人手机号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exapplicationfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/9/27', verbose_name='申请资料'),
        ),
        migrations.AlterField(
            model_name='exwarehousingapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '分管领导审批中'), ('2', '局长审批中'), ('3', '主管科室研判中'), ('4', '研判完成'), ('5', '已出库')], default='1', max_length=5, verbose_name='状态'),
        ),
    ]
