# Generated by Django 3.2 on 2022-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_application', '0018_auto_20220927_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exapplicationfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/9/28', verbose_name='申请资料'),
        ),
    ]
