# Generated by Django 4.1 on 2022-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(max_length=100, verbose_name="数据表名称")),
                ("date_str", models.CharField(max_length=100, verbose_name="日期")),
                ("number", models.IntegerField(verbose_name="自增编号")),
            ],
            options={"verbose_name": "单号自增表", "verbose_name_plural": "单号自增表",},
        ),
        migrations.CreateModel(
            name="MaterialsType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "materials_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                (
                    "specifications",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="规格"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="单位"
                    ),
                ),
                (
                    "warning_quantity",
                    models.FloatField(default=10, verbose_name="预警比例"),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("add_date", models.DateField(auto_now_add=True, verbose_name="创建日期")),
                (
                    "modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "物料种类",
                "verbose_name_plural": "物料种类",
                "unique_together": {("materials_name", "specifications", "unit")},
            },
        ),
    ]
