# Generated by Django 3.2 on 2022-09-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialstype',
            options={'ordering': ['-add_date'], 'verbose_name': '物料种类', 'verbose_name_plural': '物料种类'},
        ),
    ]
