# Generated by Django 3.2 on 2022-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_materialstype_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstype',
            name='specifications',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='规格'),
        ),
    ]
