# Generated by Django 3.2 on 2022-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_materialstype_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstype',
            name='des',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='materialstype',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='供应商电话'),
        ),
    ]
