# Generated by Django 4.1 on 2022-08-27 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ("home", "0001_initial"),
    #     migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    #     ("material_application", "__first__"),
    # ]
    #
    # operations = [
    #     migrations.CreateModel(
    #         name="CenterLibrary",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "library_name",
    #                 models.CharField(max_length=100, unique=True, verbose_name="中央库名称"),
    #             ),
    #             ("total_budget", models.FloatField(default=0, verbose_name="总预算(万元)")),
    #             (
    #                 "des",
    #                 models.CharField(
    #                     blank=True, max_length=100, verbose_name="中央库描述信息"
    #                 ),
    #             ),
    #             (
    #                 "add_time",
    #                 models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
    #             ),
    #             ("add_date", models.DateField(auto_now_add=True, verbose_name="创建日期")),
    #             (
    #                 "modify_time",
    #                 models.DateTimeField(auto_now=True, verbose_name="修改时间"),
    #             ),
    #             (
    #                 "create_user",
    #                 models.ForeignKey(
    #                     blank=True,
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to=settings.AUTH_USER_MODEL,
    #                     verbose_name="创建人",
    #                 ),
    #             ),
    #         ],
    #         options={"verbose_name": "中央库基本信息", "verbose_name_plural": "中央库基本信息",},
    #     ),
    #     migrations.CreateModel(
    #         name="CenterOutboundOrder",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "title",
    #                 models.CharField(default="", max_length=100, verbose_name="申请主题"),
    #             ),
    #             ("total_price", models.FloatField(default=0, verbose_name="出库金额")),
    #             (
    #                 "applicant",
    #                 models.CharField(default="", max_length=100, verbose_name="申请单位"),
    #             ),
    #             (
    #                 "applicant_user",
    #                 models.CharField(
    #                     default="", max_length=100, unique=True, verbose_name="领用人"
    #                 ),
    #             ),
    #             (
    #                 "des",
    #                 models.CharField(
    #                     blank=True, default="", max_length=100, verbose_name="申请说明"
    #                 ),
    #             ),
    #             (
    #                 "is_ex",
    #                 models.BooleanField(blank=True, default=False, verbose_name="是否出库"),
    #             ),
    #             (
    #                 "add_time",
    #                 models.DateTimeField(
    #                     default=django.utils.timezone.now, verbose_name="申请时间"
    #                 ),
    #             ),
    #             ("add_date", models.DateField(auto_now_add=True, verbose_name="申请日期")),
    #             (
    #                 "app_code",
    #                 models.OneToOneField(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="material_application.exwarehousingapplication",
    #                     verbose_name="出库单",
    #                 ),
    #             ),
    #         ],
    #         options={"verbose_name": "中央库出库单", "verbose_name_plural": "中央库出库单",},
    #     ),
    #     migrations.CreateModel(
    #         name="CenterWarehousingApplication",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "app_code",
    #                 models.CharField(max_length=15, unique=True, verbose_name="入库单号"),
    #             ),
    #             ("total_price", models.FloatField(default=0, verbose_name="入库总金额(万元)")),
    #             (
    #                 "des",
    #                 models.CharField(blank=True, max_length=100, verbose_name="描述"),
    #             ),
    #             (
    #                 "add_time",
    #                 models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
    #             ),
    #             ("add_date", models.DateField(auto_now_add=True, verbose_name="创建日期")),
    #             (
    #                 "modify_time",
    #                 models.DateTimeField(auto_now=True, verbose_name="修改时间"),
    #             ),
    #             (
    #                 "create_u",
    #                 models.ForeignKey(
    #                     blank=True,
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     related_name="create_u",
    #                     to=settings.AUTH_USER_MODEL,
    #                     verbose_name="创建人",
    #                 ),
    #             ),
    #         ],
    #         options={"verbose_name": "入库单", "verbose_name_plural": "入库单",},
    #     ),
    #     migrations.CreateModel(
    #         name="CenterWarehousingFile",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "file",
    #                 models.FileField(
    #                     upload_to="upload/center_library/2022/8/27",
    #                     verbose_name="(采购计划、政府采购批复、投标手续)",
    #                 ),
    #             ),
    #             (
    #                 "add_time",
    #                 models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
    #             ),
    #             (
    #                 "library_name",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="center_library.centerwarehousingapplication",
    #                     verbose_name="申请单编号",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "verbose_name": "(采购计划、政府采购批复、投标手续)等附件",
    #             "verbose_name_plural": "(采购计划、政府采购批复、投标手续)等附件",
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name="CenterLibraryFile",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "file",
    #                 models.FileField(
    #                     upload_to="upload/center_library/2022/8/27", verbose_name="附件"
    #                 ),
    #             ),
    #             (
    #                 "add_time",
    #                 models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
    #             ),
    #             (
    #                 "library_name",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="center_library.centerlibrary",
    #                     verbose_name="库名",
    #                 ),
    #             ),
    #         ],
    #         options={"verbose_name": "中央库附件", "verbose_name_plural": "中央库附件",},
    #     ),
    #     migrations.CreateModel(
    #         name="CenterLabraryQuantity",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             ("put_num", models.IntegerField(default=0, verbose_name="入库数量")),
    #             ("push_num", models.IntegerField(default=0, verbose_name="出库数量")),
    #             ("balance_num", models.IntegerField(default=0, verbose_name="结余数量")),
    #             (
    #                 "total_price",
    #                 models.FloatField(
    #                     blank=True, default=0, verbose_name="该物资入库总金额(元)"
    #                 ),
    #             ),
    #             (
    #                 "out_price",
    #                 models.FloatField(
    #                     blank=True, default=0, verbose_name="该物资出库总金额(元)"
    #                 ),
    #             ),
    #             (
    #                 "type_name",
    #                 models.OneToOneField(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="home.materialstype",
    #                     verbose_name="类型名称",
    #                 ),
    #             ),
    #         ],
    #         options={"verbose_name": "物料库存", "verbose_name_plural": "物料库存",},
    #     ),
    #     migrations.CreateModel(
    #         name="CenterOutboundOrderHistory",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "application_user",
    #                 models.CharField(blank=True, max_length=20, verbose_name="操作人"),
    #             ),
    #             (
    #                 "action",
    #                 models.CharField(default="通过", max_length=20, verbose_name="审批动作"),
    #             ),
    #             (
    #                 "add_time",
    #                 models.DateTimeField(
    #                     default=django.utils.timezone.now, verbose_name="审批时间"
    #                 ),
    #             ),
    #             (
    #                 "application",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="center_library.centeroutboundorder",
    #                     verbose_name="申请单",
    #                 ),
    #             ),
    #             (
    #                 "history_detail",
    #                 models.OneToOneField(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="material_application.applicationhistory",
    #                     verbose_name="申请单",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "verbose_name": "审批记录",
    #             "verbose_name_plural": "审批记录",
    #             "unique_together": {("application", "history_detail")},
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name="CenterOutboundOrderDetail",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "library_name",
    #                 models.CharField(max_length=1000, verbose_name="物资类型"),
    #             ),
    #             ("number", models.IntegerField(default=0, verbose_name="领用数量")),
    #             (
    #                 "app_code",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="center_library.centeroutboundorder",
    #                     verbose_name="出库单",
    #                 ),
    #             ),
    #             (
    #                 "assessment_detail",
    #                 models.OneToOneField(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="material_application.centerassessmentdetail",
    #                     verbose_name="研判详情",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "verbose_name": "中央库出库单详情",
    #             "verbose_name_plural": "中央库出库单详情",
    #             "unique_together": {("app_code", "assessment_detail")},
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name="CenterLabraryMaterials",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             ("put_num", models.IntegerField(default=0, verbose_name="入库数量")),
    #             ("unit_price", models.FloatField(default=0, verbose_name="单价(元)")),
    #             (
    #                 "total_price",
    #                 models.FloatField(blank=True, default=0, verbose_name="总金额(元)"),
    #             ),
    #             (
    #                 "add_time",
    #                 models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
    #             ),
    #             ("add_date", models.DateField(auto_now_add=True, verbose_name="创建日期")),
    #             (
    #                 "modify_time",
    #                 models.DateTimeField(auto_now=True, verbose_name="修改时间"),
    #             ),
    #             (
    #                 "type_name",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="home.materialstype",
    #                     verbose_name="类型名称",
    #                 ),
    #             ),
    #             (
    #                 "ware_app",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.DO_NOTHING,
    #                     to="center_library.centerwarehousingapplication",
    #                     verbose_name="入库单",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "verbose_name": "入库明细",
    #             "verbose_name_plural": "入库明细",
    #             "unique_together": {("ware_app", "type_name")},
    #         },
    #     ),
    # ]
