# Generated by Django 4.1 on 2022-08-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("material_application", "0002_initial"),
        ("home", "0001_initial"),
        ("center_library", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="centeroutboundorderhistory",
            name="history_detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.applicationhistory",
                verbose_name="申请单",
            ),
        ),
        migrations.AddField(
            model_name="centeroutboundorderdetail",
            name="app_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="center_library.centeroutboundorder",
                verbose_name="出库单",
            ),
        ),
        migrations.AddField(
            model_name="centeroutboundorderdetail",
            name="assessment_detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.centerassessmentdetail",
                verbose_name="研判详情",
            ),
        ),
        migrations.AddField(
            model_name="centeroutboundorder",
            name="app_code",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.exwarehousingapplication",
                verbose_name="出库单",
            ),
        ),
        migrations.AddField(
            model_name="centerlibraryfile",
            name="library_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="center_library.centerlibrary",
                verbose_name="库名",
            ),
        ),
        migrations.AddField(
            model_name="centerlibrary",
            name="create_user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="centerlabraryquantity",
            name="type_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.materialstype",
                verbose_name="类型名称",
            ),
        ),
        migrations.AddField(
            model_name="centerlabrarymaterials",
            name="type_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.materialstype",
                verbose_name="类型名称",
            ),
        ),
        migrations.AddField(
            model_name="centerlabrarymaterials",
            name="ware_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="center_library.centerwarehousingapplication",
                verbose_name="入库单",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centeroutboundorderhistory",
            unique_together={("application", "history_detail")},
        ),
        migrations.AlterUniqueTogether(
            name="centeroutboundorderdetail",
            unique_together={("app_code", "assessment_detail")},
        ),
        migrations.AlterUniqueTogether(
            name="centerlabrarymaterials", unique_together={("ware_app", "type_name")},
        ),
    ]
