# Generated by Django 4.1 on 2022-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center_library", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="centeroutboundorderdetail",
            name="total_price",
            field=models.FloatField(default=0, verbose_name="金额"),
        ),
        migrations.AlterField(
            model_name="centerlibraryfile",
            name="file",
            field=models.FileField(
                upload_to="upload/center_library/2022/8/28", verbose_name="附件"
            ),
        ),
        migrations.AlterField(
            model_name="centerwarehousingfile",
            name="file",
            field=models.FileField(
                upload_to="upload/center_library/2022/8/28",
                verbose_name="(采购计划、政府采购批复、投标手续)",
            ),
        ),
    ]
