# Generated by Django 4.1 on 2022-08-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center_library", "0004_centeroutboundorderdetail_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centeroutboundorderdetail", name="library_name",
        ),
        migrations.AddField(
            model_name="centerwarehousingapplication",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="upload/center_library/2022/8/28",
                verbose_name="入库明细(excel)",
            ),
        ),
    ]
