# Generated by Django 3.2 on 2022-09-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center_library', '0010_auto_20220903_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerlabrarymaterials',
            options={'ordering': ['-add_time'], 'verbose_name': '入库明细', 'verbose_name_plural': '入库明细'},
        ),
        migrations.AlterModelOptions(
            name='centerlibrary',
            options={'ordering': ['-add_date'], 'verbose_name': '中央库基本信息', 'verbose_name_plural': '中央库基本信息'},
        ),
        migrations.AlterModelOptions(
            name='centerwarehousingapplication',
            options={'ordering': ['-add_date'], 'verbose_name': '入库单', 'verbose_name_plural': '入库单'},
        ),
    ]
