# Generated by Django 3.2 on 2022-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_library', '0011_auto_20220903_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerlabraryquantity',
            options={'verbose_name': '中央库物料库存', 'verbose_name_plural': '中央库物料库存'},
        ),
        migrations.AlterModelOptions(
            name='centerwarehousingapplication',
            options={'ordering': ['-add_date'], 'verbose_name': '中央库入库单', 'verbose_name_plural': '中央库入库单'},
        ),
        migrations.AlterField(
            model_name='centerlibraryfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/9/4', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='centerwarehousingapplication',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/center_library/2022/9/4', verbose_name='入库明细(excel)'),
        ),
        migrations.AlterField(
            model_name='centerwarehousingfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/9/4', verbose_name='(采购计划、政府采购批复、投标手续)'),
        ),
    ]
