# Generated by Django 3.2 on 2022-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_library', '0012_auto_20220904_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centeroutboundorder',
            name='applicant_user',
            field=models.CharField(default='', max_length=100, verbose_name='领用人'),
        ),
    ]
