# Generated by Django 3.2 on 2022-11-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_library', '0016_auto_20220929_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeroutboundorderdetail',
            name='des',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='centerlibraryfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/11/25', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='centerwarehousingapplication',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/center_library/2022/11/25', verbose_name='入库明细(excel)'),
        ),
        migrations.AlterField(
            model_name='centerwarehousingfile',
            name='file',
            field=models.FileField(upload_to='upload/center_library/2022/11/25', verbose_name='(采购计划、政府采购批复、投标手续)'),
        ),
    ]
