# Generated by Django 4.1 on 2022-08-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("material_application", "0002_initial"),
        ("home", "0001_initial"),
        ("local_library", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="localoutboundorderhistory",
            name="history_detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.applicationhistory",
                verbose_name="申请单",
            ),
        ),
        migrations.AddField(
            model_name="localoutboundorderdetail",
            name="app_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="local_library.localoutboundorder",
                verbose_name="出库单",
            ),
        ),
        migrations.AddField(
            model_name="localoutboundorderdetail",
            name="assessment_detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.localassessmentdetail",
                verbose_name="研判详情",
            ),
        ),
        migrations.AddField(
            model_name="localoutboundorder",
            name="app_code",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.exwarehousingapplication",
                verbose_name="出库单",
            ),
        ),
        migrations.AddField(
            model_name="localoutboundorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="供应商",
            ),
        ),
        migrations.AddField(
            model_name="locallibrary",
            name="create_user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="create_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="locallibrary",
            name="supplier_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="local_library.suppliermessage",
                verbose_name="供应商",
            ),
        ),
        migrations.AddField(
            model_name="locallabrarymaterials",
            name="library_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="local_library.locallibrary",
                verbose_name="库名",
            ),
        ),
        migrations.AddField(
            model_name="locallabrarymaterials",
            name="type_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.materialstype",
                verbose_name="物资类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="localoutboundorderhistory",
            unique_together={("application", "history_detail")},
        ),
        migrations.AlterUniqueTogether(
            name="localoutboundorderdetail",
            unique_together={("app_code", "assessment_detail")},
        ),
        migrations.AlterUniqueTogether(
            name="localoutboundorder", unique_together={("app_code", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="locallabrarymaterials",
            unique_together={("library_name", "type_name")},
        ),
    ]
