# Generated by Django 4.1 on 2022-08-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("local_library", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localoutboundorder",
            options={"verbose_name": "地方库库出库单", "verbose_name_plural": "地方库库出库单"},
        ),
        migrations.AlterField(
            model_name="locallibrary",
            name="budget",
            field=models.FloatField(default=0, verbose_name="预算(万元)"),
        ),
        migrations.AlterField(
            model_name="locallibrary",
            name="des",
            field=models.CharField(blank=True, max_length=100, verbose_name="入库描述"),
        ),
        migrations.AlterField(
            model_name="locallibrary",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="upload/local_library/2022/8/27",
                verbose_name="入库明细(excel)",
            ),
        ),
        migrations.AlterField(
            model_name="locallibrary",
            name="is_approve",
            field=models.BooleanField(default=0, verbose_name="审核通过"),
        ),
        migrations.AlterField(
            model_name="locallibrary",
            name="less_budget",
            field=models.FloatField(default=0, verbose_name="剩余预算(万元)"),
        ),
        migrations.AlterField(
            model_name="localwarehousingfile",
            name="library_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="local_library.locallibrary",
                verbose_name="入库单编号",
            ),
        ),
        migrations.AlterField(
            model_name="supplierfile",
            name="library_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="local_library.suppliermessage",
                verbose_name="地方库供应商",
            ),
        ),
    ]
