# Generated by Django 4.1 on 2022-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_library", "0004_alter_localoutboundorder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localoutboundorderdetail",
            name="total_price",
            field=models.FloatField(default=0, verbose_name="金额"),
        ),
        migrations.AlterField(
            model_name="locallibrary",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="upload/local_library/2022/8/28",
                verbose_name="入库明细(excel)",
            ),
        ),
        migrations.AlterField(
            model_name="localwarehousingfile",
            name="file",
            field=models.FileField(
                upload_to="upload/local_library/2022/8/28",
                verbose_name="(采购计划、政府采购批复、投标手续)",
            ),
        ),
        migrations.AlterField(
            model_name="supplierfile",
            name="file",
            field=models.FileField(
                upload_to="upload/local_library/2022/8/28", verbose_name="(供应商附件)"
            ),
        ),
    ]
