# Generated by Django 4.1 on 2022-08-28 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("local_library", "0005_localoutboundorderdetail_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localoutboundorder",
            name="total_price",
            field=models.FloatField(blank=True, default=0, verbose_name="总金额(元)"),
        ),
        migrations.AlterField(
            model_name="localoutboundorderhistory",
            name="action",
            field=models.CharField(default="通过", max_length=20, verbose_name="审批意见"),
        ),
        migrations.AlterField(
            model_name="localoutboundorderhistory",
            name="add_time",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="审批时间"
            ),
        ),
    ]
