# Generated by Django 4.1 on 2022-08-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("material_application", "0007_localassessmentdetail_total_price_and_more"),
        ("local_library", "0006_alter_localoutboundorder_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localoutboundorderdetail", name="library_name",
        ),
        migrations.RemoveField(model_name="localoutboundorderdetail", name="number",),
        migrations.AlterField(
            model_name="localoutboundorderdetail",
            name="assessment_detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="material_application.localassessmentdetail",
                verbose_name="物资详情",
            ),
        ),
        migrations.AlterField(
            model_name="localoutboundorderdetail",
            name="total_price",
            field=models.FloatField(default=0, verbose_name="金额(元)"),
        ),
    ]
