# Generated by Django 4.1 on 2022-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_library", "0007_remove_localoutboundorderdetail_library_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localoutboundorderdetail",
            name="number",
            field=models.IntegerField(default=0, verbose_name="数量"),
        ),
    ]
