# Generated by Django 3.2 on 2022-08-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_library', '0008_localoutboundorderdetail_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locallabrarymaterials',
            name='library_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_library.locallibrary', verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='locallibrary',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/local_library/2022/8/29', verbose_name='入库明细(excel)'),
        ),
        migrations.AlterField(
            model_name='localwarehousingfile',
            name='file',
            field=models.FileField(upload_to='upload/local_library/2022/8/29', verbose_name='(采购计划、政府采购批复、投标手续)'),
        ),
        migrations.AlterField(
            model_name='supplierfile',
            name='file',
            field=models.FileField(upload_to='upload/local_library/2022/8/29', verbose_name='(供应商附件)'),
        ),
    ]
