# Generated by Django 3.2 on 2022-09-01 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local_library', '0012_auto_20220901_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localoutboundorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='供应商'),
        ),
    ]
