# Generated by Django 3.2 on 2022-09-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_library', '0014_auto_20220903_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locallibrary',
            options={'ordering': ['-add_time'], 'permissions': [('can_approve', '是否可以审核入库单')], 'verbose_name': '入库单', 'verbose_name_plural': '入库单'},
        ),
        migrations.AlterModelOptions(
            name='localwarehousingfile',
            options={'ordering': ['-add_time'], 'verbose_name': '(采购计划、政府采购批复、投标手续)', 'verbose_name_plural': '(采购计划、政府采购批复、投标手续)'},
        ),
        migrations.AlterModelOptions(
            name='supplierfile',
            options={'ordering': ['-add_time'], 'verbose_name': '(供应商附件)', 'verbose_name_plural': '(供应商附件)'},
        ),
        migrations.AlterModelOptions(
            name='suppliermessage',
            options={'ordering': ['-add_time'], 'verbose_name': '地方库', 'verbose_name_plural': '地方库'},
        ),
    ]
