# Generated by Django 3.2 on 2022-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_library', '0015_auto_20220903_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locallibrary',
            options={'ordering': ['-add_time'], 'permissions': [('can_approve', '是否可以审核入库单')], 'verbose_name': '地方库入库单', 'verbose_name_plural': '地方库入库单'},
        ),
        migrations.AlterModelOptions(
            name='localoutboundorder',
            options={'permissions': [('chaneg_is_ex', '是否可以出库'), ('chaneg_is_check', '是否可以核销')], 'verbose_name': '地方库出库单', 'verbose_name_plural': '地方库出库单'},
        ),
        migrations.AlterModelOptions(
            name='suppliermessage',
            options={'ordering': ['-add_time'], 'verbose_name': '地方库信息', 'verbose_name_plural': '地方库信息'},
        ),
        migrations.AlterField(
            model_name='locallibrary',
            name='file',
            field=models.FileField(blank=True, upload_to='upload/local_library/2022/9/4', verbose_name='入库明细(excel)'),
        ),
        migrations.AlterField(
            model_name='localoutboundorder',
            name='applicant_user',
            field=models.CharField(default='', max_length=100, verbose_name='领用人'),
        ),
        migrations.AlterField(
            model_name='localwarehousingfile',
            name='file',
            field=models.FileField(upload_to='upload/local_library/2022/9/4', verbose_name='(采购计划、政府采购批复、投标手续)'),
        ),
        migrations.AlterField(
            model_name='supplierfile',
            name='file',
            field=models.FileField(upload_to='upload/local_library/2022/9/4', verbose_name='(供应商附件)'),
        ),
    ]
